### PR TITLE
Android Studio custom template #14

### PR DESCRIPTION
**Pull request by spili**
AndroidViewModel template for Android Studio.
#### Usage
1. Copy the `ViewModelActivity` folder to Android Studio templates folder (`/Applications/Android Studio.app/Contents/plugins/android/lib/templates/activities`)
2. Restart Android Studio
3. Use `File> New >AndroidViewModel>AndroidViewModel Screen` action to add a new screen

### CODE REVIEW

**Comment by yuraj11** [comment]
There is no "implements IView" after ViewModelBaseFragment / ViewModelBaseActivity. Also you should add setModelView in onViewCreated / onCreate.

**Comment by spili** [comment]
Sorry for all this mess, it was all because i wasn't able to edit template from AS (now for template editing i'm using IntelliJ IDEA). 
To sum it up: template is reviewed, tested and should work now ...

**Comment by yuraj11** [comment]
:+1:

**Comment by yuraj11** [comment]
We have to wait until Google fixes this issue https://goo.gl/wAqK0s

**Comment by spili** [comment]
Closing in favour of newer [PR #33](https://github.com/inloop/AndroidViewModel/pull/33).

**Pull request closed without merging**
