### PR TITLE
Removed reflection

### PR DESCRIPTION
**Pull request by LosoncziTamas**
I replaced the class.newInstance() by creating a factory interface. This way the ViewModel classes are easier to test, we can pass dependencies in it's constructor. 
Since these are quite big changes in the API, I won't expect to approve this pull request. But I would still suggest considering similar updates in the future.

### CODE REVIEW

**Comment by DanielNovak** [comment]
Thank you very much for this PR. I haven't looked into detail yet. The problem with passing arguments into the constructor is that the actual use case is a bit limited - since the `createViewModel()` is called very early - along when the Activity or Fragment is created. So there is not much else to forward except an Bundle from intent extras or arguments - which is already done by a different mechanism here.

@LosoncziTamas Can you maybe provide an example where you need to forward a dependency into the ViewModel class by a constructor? I usually have a "service locator" class that I am using to inject something like `ApiService` or `DbService` - but this doesn't rely on constructor. Maybe if you are using Dagger then you need a parametrised constructor?

**Comment by LosoncziTamas** [comment]
Since the ViewModel classes are usually perform the heavy work (ex.: data conversion/validation) I wanted to make it testable. The best way to do it is by passing all the dependencies in the constructor.  A very basic example for this:
```java
public class MainViewModel extends AbstractViewModel<MainView> { 

	public final CounterEntity counterEntity; 

	private final MainNavigator mainNavigator;

	@Inject
	public MainViewModel(CounterEntity counterEntity, MainNavigator mainNavigator) {
		this. counterEntity = counterEntity;
		this. navigator = mainNavigator;
	}

	public void onCounterButtonClicked() {
		counterEntity.increment();
		mainNavigator.openSecondaryScreen();
	}
}
```

The entity is a subclass of BaseObservable the MainNavigator is an abstraction for the navigation between the activities.
 
The fragment will look something like this:

```java
public class MainFragment extends ViewModelBaseFragment<MainView, MainViewModel> implements MainView, IViewModelFactory<MainView> {

    @Inject
    Lazy<MainViewModel> viewModelInjector;

    private MainViewModel mainViewModel;

    private FragmentMainBinding binding;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        inject(this);
        super.onCreate(savedInstanceState);
        mainViewModel = getViewModel();
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        binding = FragmentMainBinding.inflate(inflater);
        binding.setView(this);
        binding.setViewModel(mainViewModel);
        return mBinding.getRoot();
    }


    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        setView(this); // I renamed the setViewModel() to setView()
    }

    @Override
    public void onCounterButtonClicked(View view) {
        mainViewModel.onCounterButtonClicked();
    }

    @Override
    public ViewModelFactory getViewModelFactory() {
        return this;
    }

    @Override
    public AbstractViewModel<MainView> createViewModel() {
        return viewModelInjector.get();
    }
}
```

As you can see I'm using Dagger here to inject the ViewModel.

The benefits in all this that the ViewModel is not relying on any static call, it is independent of the Android framework itself (in this example by using a Navigator Interface instead of an Activity) so it can be tested with JUnit.

**Comment by DanielNovak** [comment]
@LosoncziTamas Thank you for providing an example. This definitely makes sense. We will take a look at this today and think about integrating this into AndroidViewModel - I am not sure yet if this can be achieved without breaking changes.

**Comment by DanielNovak** [comment]
@LosoncziTamas I think we could do this with backwards compatibility. The `getViewModelClass()` will not be abstract anymore and will return `null` by default and will be deprecated. The ViewModelHelper.onCreate() will have two versions (two methods), one that takes a Class and the second one that takes an instance (your approach). If you have an existing code and you are using getViewModelClass() then we will just create an instance of the ViewModel with the empty constructor and forward it to the new code proposed by you.

I will probably open a new pulll request for this, because I need to add the compatibility code. I would like to keep you as an author / contributor, because this was your PR and your idea :-). I am not sure how to achieve that yet.

**Comment by DanielNovak** [comment]
@LosoncziTamas Can you take a look at https://github.com/inloop/AndroidViewModel/pull/21 ? 
I am wondering if we should also add another fragment or modify one of the existing ones in the sample to show how to use DI with AndroidViewModel and maybe also a JUnit test.

**Comment by LosoncziTamas** [comment]
Thanks for considering my request. I'll take a look at [#21](https://github.com/inloop/AndroidViewModel/pull/21) later today.

**Comment by DanielNovak** [comment]
Hi @LosoncziTamas - sorry for not taking a look at your PR again, I was focused on other tasks but I still plan to return back to it. We released 1.2.0 in the mean time with some changes. Maybe you can rebase and squash the commits into a single one?

**Comment by LosoncziTamas** [comment]
Okay, will do it.

**Comment by LosoncziTamas** [comment]
Hi @DanielNovak I created a separate request including all the changes, squashed into one commit. Please take a look at #27.

**Comment by DanielNovak** [comment]
Thanks for all the effort on this, I will take another look at this today.

**Comment by petrnohejl** [comment]
Hi @DanielNovak Any progress on this PR? It would be really great to have this functionality in the library. Thanks.

**Comment by Taig** [comment]
Facing the same use case here. This feature would improve code testability significantly.

**Comment by DanielNovak** [comment]
@Taig @LosoncziTamas Unfortunately it's not that easy now with the latest version of AVM. The getViewModelClass() is now optional - you don't need to implement it, we can extract the ViewModel class from the class definition (generic). This is fine for most people - it's one less method they need to implement. 
But we would need to keep it compatibile - so I can't just add a createViewModelClass() - I need to check whether the user actually implemented that method (without creating the instance). 
So here is an implementation that works (and doesn't the users to implement getViewModelFactory() if they are OK with reflection):
https://github.com/inloop/AndroidViewModel/compare/injection

The huge disadvantage is that you need to write an anonymous and long method in the implementation Activity/Fragment like this:

    @Nullable
    @Override
    public IViewModelFactory<IUserListView, UserListViewModel> getViewModelFactory() {
        return new  IViewModelFactory<IUserListView, UserListViewModel>() {
            @Nullable
            @Override
            public UserListViewModel createViewModel() {
                return new UserListViewModel();
            }
        };
    }

Any thoughts how to make it work for people that don't want to implement getViewModelClass / createViewModel?

**Comment by petrnohejl** [comment]
Hi @DanielNovak. Any news regarding this PR? What about to make a breaking change, add this factory functionality and publish a new version of AVM 2.0.0?

You could support all 3 ways of creating view model instance:
- Default (with reflection)
- By class reference
- By factory

Adding the view model factory would be a big step forward and many developers would appreciate it. Thanks.

**Comment by DanielNovak** [comment]
@petrnohejl No news - but I am fine with breaking changes for 2.0.0 as long as the migration won't be that complicated. It has been quite a long time since the PR is opened and I forgot how we wanted to approach the problem :-). But I think there could be a default implementation is creating instances based on reflection. Then you could override it to change the behavior to class reference / factory...  If you have anything that works then feel free to open a new PR - we can close this one and start from scratch.

**Pull request closed without merging**
